services:
  spark:
    image: spark:4.0.0-java21
    restart: always
    container_name: spark
    network_mode: host
    command: /opt/spark/sbin/start-connect-server.sh --wait
    environment:
      - SPARK_EXECUTOR_CORES=12
      - SPARK_EXECUTOR_MEMORY=16G
      - SPARK_DRIVER_MEMORY=8G